<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function smart_content_funnelenvy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the smart_content_funnelenvy module.
    case 'help.page.smart_content_funnelenvy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Connector module for FunnelEnvy') . '</p>';
      return $output;

    default:
  }
}
